export ZSH="/home/kev/.oh-my-zsh"

# Setup theme for terminal 
POWERLEVEL9K_MODE='awesome-fontconfig'
ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_DIR_SHOW_WRITABLE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='\uf0da'
POWERLEVEL9K_HOME_ICON='\uF6F1 '
POWERLEVEL9K_HOME_SUB_ICON='\uF6F1 '
POWERLEVEL9K_LOCK_ICON='\uF115 '
POWERLEVEL9K_FOLDER_ICON='\uF07C '

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='yellow'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='yellow'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4

# VPS 
alias invert="xcalib -invert -alter"
alias tunnel="ssh kev@35.247.158.252 -p55222 -fN -D 1503"
alias sshvps="ssh kev@35.247.158.252 -p55222"

# set enviroments
export JAVA_HOME=/usr/lib/jvm/default-java
export JRE_HOME=/usr/lib/jvm/default-java/jre

source $ZSH/oh-my-zsh.sh
